spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: cggtsds59@gmail.com
    password: nado mcnm iuxw bbla
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true